language: java
cache:
  directories:
  - $HOME/.m2
sudo: false
jdk:
- oraclejdk8
before_install:
- export MAVEN_OPTS="-Xmx768M"
- chmod +x ./gradlew
- chmod +x ./BuildDevint
script:
- ./BuildDevint -q
